const BASE_TICKERS = [
  "AAPL",
  "MSFT",
  "AMZN",
  "GOOGL",
  "GOOG",
  "META",
  "NVDA",
  "BRK.B",
  "TSLA",
  "JPM",
  "V",
  "UNH",
  "XOM",
  "JNJ",
  "WMT",
  "PG",
  "MA",
  "HD",
  "LLY",
  "ABBV",
  "AVGO",
  "COST",
  "CVX",
  "KO",
  "PEP",
  "MRK",
  "BAC",
  "TMO",
  "CSCO",
  "ACN",
  "DIS",
  "MCD",
  "ABT",
  "DHR",
  "WFC",
  "ADBE",
  "NEE",
  "PM",
  "CRM",
  "NFLX",
  "TXN",
  "VZ",
  "LIN",
  "ORCL",
  "INTC",
  "AMD",
  "QCOM",
  "RTX",
  "HON",
  "IBM"
];

export const ALLOWED_TICKERS = new Set(BASE_TICKERS);

export const ASSET_NAME_BY_TICKER: Record<string, string> = {
  AAPL: "Apple Inc.",
  MSFT: "Microsoft Corporation",
  AMZN: "Amazon.com, Inc.",
  GOOGL: "Alphabet Inc. Class A",
  GOOG: "Alphabet Inc. Class C",
  META: "Meta Platforms, Inc.",
  NVDA: "NVIDIA Corporation",
  "BRK.B": "Berkshire Hathaway Inc. Class B",
  TSLA: "Tesla, Inc.",
  JPM: "JPMorgan Chase & Co.",
  V: "Visa Inc.",
  UNH: "UnitedHealth Group Incorporated",
  XOM: "Exxon Mobil Corporation",
  JNJ: "Johnson & Johnson",
  WMT: "Walmart Inc.",
  PG: "Procter & Gamble Co.",
  MA: "Mastercard Incorporated",
  HD: "The Home Depot, Inc.",
  LLY: "Eli Lilly and Company",
  ABBV: "AbbVie Inc.",
  AVGO: "Broadcom Inc.",
  COST: "Costco Wholesale Corporation",
  CVX: "Chevron Corporation",
  KO: "The Coca-Cola Company",
  PEP: "PepsiCo, Inc.",
  MRK: "Merck & Co., Inc.",
  BAC: "Bank of America Corporation",
  TMO: "Thermo Fisher Scientific Inc.",
  CSCO: "Cisco Systems, Inc.",
  ACN: "Accenture plc",
  DIS: "The Walt Disney Company",
  MCD: "McDonald's Corporation",
  ABT: "Abbott Laboratories",
  DHR: "Danaher Corporation",
  WFC: "Wells Fargo & Company",
  ADBE: "Adobe Inc.",
  NEE: "NextEra Energy, Inc.",
  PM: "Philip Morris International Inc.",
  CRM: "Salesforce, Inc.",
  NFLX: "Netflix, Inc.",
  TXN: "Texas Instruments Incorporated",
  VZ: "Verizon Communications Inc.",
  LIN: "Linde plc",
  ORCL: "Oracle Corporation",
  INTC: "Intel Corporation",
  AMD: "Advanced Micro Devices, Inc.",
  QCOM: "QUALCOMM Incorporated",
  RTX: "RTX Corporation",
  HON: "Honeywell International Inc.",
  IBM: "International Business Machines Corporation"
};

export function isAllowedTicker(ticker: string) {
  return ALLOWED_TICKERS.has(ticker.toUpperCase());
}

export function getAssetName(ticker: string) {
  return ASSET_NAME_BY_TICKER[ticker.toUpperCase()] ?? "";
}
